
FIND_PATH(OPENLDAP_INCLUDES ldif.h
  HINTS
  ${OPENLDAP_DIR}
  $ENV{OPENLDAP_DIR}
  /usr
  PATH_SUFFIXES include
)

FIND_LIBRARY(OPENLDAP_LIB ldap
  HINTS
  ${OPENLDAP_DIR}
  $ENV{OPENLDAP_DIR}
  /usr
  PATH_SUFFIXES lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenLdap DEFAULT_MSG OPENLDAP_LIB OPENLDAP_INCLUDES)

